interiorStudio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('', include('planit.urls', namespace='')),
    path('captcha/', include('captcha.urls')),
    path('superadmin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

planit/urls.py
from django.urls import path
from .views import index,ApplicationView,BBLoginView, BBLogoutView,BBLogoutConfirmationView,ApplicationDelete,RegisterUserView,RegisterDoneView,user_activate,UpdateApplicationStatusView,CategoryListView,CategoryCreateView,CategoryDeleteView,ApplicationDetailView,WatchApplication
app_name = 'planit'

urlpatterns = [
    path('', index, name='index'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('login', BBLoginView.as_view(), name='login'),
    path('accounts/profile/', index, name='login_success' ),
    path('logout/confirm/', BBLogoutConfirmationView.as_view(), name='logout_confirm'),
    path('logout/', BBLogoutView.as_view(), name='logout'),
    path('create_application/', ApplicationView.as_view(), name='create_application'),
    path('watch_application/', WatchApplication.as_view() , name='watch_application'),
    path('application/<int:pk>/update/', UpdateApplicationStatusView.as_view(), name='update_application'),
    path('application/<int:pk>/', ApplicationDetailView.as_view(), name='application_detail'),
    path('application/<int:pk>/delete/', ApplicationDelete.as_view() , name='delete_application'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/add/', CategoryCreateView.as_view(), name='add_category'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='delete_category'),
]

planit/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.dispatch import Signal
from .utilities import send_activation_notification
user_registrated = Signal('instance')

class AdvUser(AbstractUser): 
    middle_name = models.CharField(max_length=30, blank=True, verbose_name='Отчество')
    is_activated = models.BooleanField(default=True, 
    db_index=True, verbose_name='Прошел активацию?') 
    personal_data = models.BooleanField(default=True, 
    verbose_name='Я согласен на обработку персональных данных',null=False, blank=False) 
class Meta(AbstractUser.Meta): 
    pass

def user_registrated_dispatcher(sender, **kwargs):
   send_activation_notification(kwargs['instance'])


user_registrated.connect(user_registrated_dispatcher)




class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name
    
    
class Application(models.Model):
    STATUS_CHOICES = [
        ('new', 'Новая'),
        ('in_progress', 'Принято в работу'),
        ('completed', 'Выполнено'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь')
    title = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    image = models.ImageField(upload_to='applications/', null=True, blank=True, verbose_name='Изображение')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new', verbose_name='Статус')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    comment = models.TextField(null=True, blank=True, verbose_name='Комментарий')
    assigned_admin = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='assigned_applications', verbose_name='Назначенный администратор')
    def __str__(self):
        return self.title
    
class ApplicationChangeHistory(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE, related_name='change_history')
    new_status = models.CharField(max_length=20)
    changed_at = models.DateTimeField(auto_now_add=True)
    changed_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    comment = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.application.title} changed from {self.previous_status} to {self.new_status} on {self.changed_at}"

planit/forms.py
from django import forms
from captcha.fields import CaptchaField
from .models import Application
from django.core.exceptions import ValidationError
from .models import AdvUser
from django.contrib.auth import password_validation
from .models import user_registrated
from django import forms
from .models import AdvUser
from django.core.exceptions import ValidationError
from django.contrib.auth import password_validation
from .models import user_registrated


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['title', 'description', 'category', 'image'] 

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if not title:
            raise forms.ValidationError("Это поле обязательно для заполнения.")
        return title

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if not description:
            raise forms.ValidationError("Это поле обязательно для заполнения.")
        return description

    def clean_image(self):
        image = self.cleaned_data.get('image')
        if image and image.size > 2 * 1024 * 1024:  # 2MB limit
            raise forms.ValidationError("Размер изображения не должен превышать 2 МБ.")
        return image

    def clean_category(self):
        category = self.cleaned_data.get('category')
        if not category:
            raise forms.ValidationError("Выберите категорию.")
        return category

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data


class RegisterUserForm(forms.ModelForm):
    username = forms.CharField(
        label='Имя',  
        required=True
    )
    last_name = forms.CharField(
        label='Фамилия', 
        required=True
    )
    middle_name = forms.CharField(
        label='Отчество',
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Отчество (если есть)'})
    )
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html()
    )
    password2 = forms.CharField(
        label='Пароль (повторно)',
        widget=forms.PasswordInput,
        help_text='Повторите тот же самый пароль еще раз'
    )
    personal_data = forms.BooleanField(
        required=True,
        label='Я согласен на обработку персональных данных',
        error_messages={'required': 'Необходимо согласие на обработку данных.'}
    )

    captcha = CaptchaField(label='Введите код с картинки')

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        
        if password1 and password2 and password1 != password2:
            raise ValidationError('Введенные пароли не совпадают.')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False  
        user.is_activated = False  
        if commit:
            user.save()
            user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username','last_name', 'middle_name', 'email', 'password1', 'password2','personal_data','captcha')


class UpdateApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['status', 'image', 'comment']  

    def clean(self):
        cleaned_data = super().clean()
        status = cleaned_data.get('status')
        image = cleaned_data.get('image')
        comment = cleaned_data.get('comment')

        if self.instance.status == 'new':
            if status == 'completed' and not image:
                raise forms.ValidationError("При смене статуса на 'Выполнено' необходимо прикрепить изображение.")
            if status == 'in_progress' and not comment:
                raise forms.ValidationError("При смене статуса на 'Принято в работу' необходимо указать комментарий.")

        if self.instance.status == 'in_progress':
            if status == 'completed' and not image:
                raise forms.ValidationError("При смене статуса на 'Выполнено' необходимо прикрепить изображение.")

        if self.instance.status in ['completed']:
            raise forms.ValidationError("Смена статуса невозможна с текущего состояния.")

        return cleaned_data

planit/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View 
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView,LogoutView
from django.views.generic import ListView
from django.views.generic.edit import CreateView,UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Application,AdvUser,Category
from .forms import ApplicationForm,RegisterUserForm,UpdateApplicationForm
from django.urls import reverse_lazy
from django.contrib import messages
from django.core.signing import BadSignature
from .models import ApplicationChangeHistory
from django.db.models import Q  
from .utilities import signer

def index(request):
    applications = Application.objects.filter(status='completed').order_by('-created_at')[:4]
    in_progress_count = Application.objects.filter(status='in_progress').count()
    return render(request, 'application/watch_application.html', {
        'applications': applications,
        'is_index_page': True,
        'in_progress_count': in_progress_count
    })

class RegisterUserView(CreateView):
   model = AdvUser
   template_name = 'user/register_user.html'
   form_class = RegisterUserForm
   success_url = reverse_lazy('planit:register_done')


class RegisterDoneView(TemplateView):
   template_name = 'user/register_done.html'

def user_activate(request, sign):
   try:
       username = signer.unsign(sign)
   except BadSignature:
       return render(request, 'user/bad_signature.html')
   user = get_object_or_404(AdvUser, username=username)
   if user.is_activated:
       template = 'user/user_is_activated.html'
   else:
       template = 'user/activation_done.html'
       user.is_activated = True
       user.is_active = True
       user.save()
   return render(request, template)


class BBLoginView(LoginView):
    template_name = 'user/login.html'
    
    def form_valid(self, form):
        messages.success(self.request, "Вы успешно вошли в систему!")
        return super().form_valid(form)

class BBLogoutConfirmationView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'user/confirm_logout.html')
        
class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'user/logged_out.html'



class ApplicationView(CreateView):
    model = Application
    form_class = ApplicationForm
    template_name = 'application/create_application.html'
    success_url = '/'

    def form_valid(self, form):
        form.instance.user = self.request.user  
        messages.success(self.request, 'Заявка успешно создана!')
        return super().form_valid(form)
    

class WatchApplication(LoginRequiredMixin, ListView):
    model = Application
    template_name = 'application/watch_application.html'  
    context_object_name = 'applications' 

    def get_queryset(self):
        queryset = super().get_queryset()

        # Проверяем, является ли пользователь суперпользователем
        if self.request.user.is_superuser:
            return queryset  # Если да, возвращаем все заявки

        # Проверяем, состоит ли пользователь в группе "administrators"
        if self.request.user.groups.filter(name='administrators').exists():
            # только заявки, созданные суперпользователем
            return queryset.filter(user__is_superuser=True)

        # Если пользователь не суперпользователь и не администратор, только его заявки
        return queryset.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['statuses'] = Application.STATUS_CHOICES
        context['is_index_page'] = False  
        
        return context

class UpdateApplicationStatusView(LoginRequiredMixin, UpdateView):
    model = Application
    form_class = UpdateApplicationForm
    template_name = 'application/update_application.html'  
    success_url = reverse_lazy('planit:watch_application')

    def dispatch(self, request, *args, **kwargs):
        # является ли суперпользователем или администратором
        if not (request.user.is_superuser or request.user.groups.filter(name='administrators').exists()):
            messages.error(request, "У вас нет прав для изменения статуса заявки.")
            return redirect('planit:watch_application')  
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        new_status = form.cleaned_data['status'] 
        form.instance.user = self.object.user  
        response = super().form_valid(form)  
        comment = form.cleaned_data.get('comment')
        ApplicationChangeHistory.objects.create(
            application=self.object, 
            new_status=new_status, 
            changed_by=self.request.user,
            comment=comment if new_status == 'in_progress' else None 
        )
        
        messages.success(self.request, 'Статус заявки успешно обновлён!')
        return response


class ApplicationDetailView(DetailView):
    model = Application
    template_name = 'application/application_detail.html'  
    context_object_name = 'application' 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['change_history'] = self.object.change_history.all()  
        return context

class ApplicationDelete(LoginRequiredMixin, DeleteView):
    model = Application
    template_name = 'application/application_confirm_delete.html'  
    success_url = reverse_lazy('planit:watch_application') 

    def get_queryset(self):
        if self.request.user.is_superuser or self.request.user.groups.filter(name='administrators').exists():
            return Application.objects.all()
        return Application.objects.filter(user=self.request.user)

    def dispatch(self, request, *args, **kwargs):
        if not (request.user.is_superuser or request.user.groups.filter(name='administrators').exists()):
            messages.error(request, "У вас нет прав для удаления заявки.")
            return redirect('planit:watch_application')
        return super().dispatch(request, *args, **kwargs)

class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = 'category/category_list.html' 
    context_object_name = 'categories'


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    fields = ['name']
    template_name = 'category/category_form.html'  
    success_url = reverse_lazy('planit:category_list')  

    def form_valid(self, form):
        messages.success(self.request, "Категория успешно добавлена.")
        return super().form_valid(form)


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = Category
    template_name = 'category/category_confirm_delete.html'  
    success_url = reverse_lazy('planit:category_list')

    def delete(self, request, *args, **kwargs):
        category = self.get_object()
        applications_count = Application.objects.filter(category=category).count()
        Application.objects.filter(category=category).delete()  
        
        messages.success(request, f'Категория "{category.name}" и все связанные заявки (всего {applications_count}) успешно удалены.')
        return super().delete(request, *args, **kwargs)

planit/templates/application/application_confirm_delete.html
{% extends "layout/base.html" %}

{% block content %}
  <div class="logout-confirmation">
    <h2>Вы действительно хотите удалить заявку?</h2>
    <div class="button-group d-flex mt-4">  
        <form action="" method="post" class="mr-2"> 
            {% csrf_token %}
            <button class="btn btn-danger">Да</button>
        </form>
        <a href="{% url 'planit:watch_application' %}" class="btn btn-secondary">Нет</a>
        
    </div>
  </div>
{% endblock %}

planit/templates/application/application_detail.html
{% extends "layout/base.html" %}

{% block content %}
<h3>История изменений</h3>
<ul>
    {% for change in application.change_history.all %}
        <li>{{ change.changed_at|date:"d.m.Y H:i" }}: → {{ change.new_status }} (Изменил: {{ change.changed_by.username }})</li>
        {% if change.new_status == 'in_progress' and change.comment %}
            <ul>
                <li><strong>Комментарий:</strong> {{ change.comment }}</li>
            </ul>
        {% endif %}
    {% empty %}
        <li>Нет истории изменений.</li>
    {% endfor %}
</ul>
{% endblock %}

planit/templates/application/create_application.html
{% extends "layout/base.html" %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4">Создать заявку</h2>

    {% if user.is_authenticated %}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }} 
            </div>
            <button type="submit" class="btn create-btn ">Создать заявку</button>
        </form>
    {% else %}
        <p>Пожалуйста, <a href="#">войдите</a>, чтобы создать заявку.</p>
    {% endif %}
</div>
{% endblock %}

planit/templates/application/update_application.html
{% extends "layout/base.html" %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4">Изменить статус заявки</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn create-btn">Сохранить изменения</button>
    </form>
</div>
{% endblock %}

planit/templates/application/watch_application.html
{% extends "layout/base.html" %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4">Список заявок</h2>
    {% if is_index_page %}
    <div class="alert alert-info">
        <strong>Количество заявок в статусе "Принято в работу":</strong> {{ in_progress_count }}
    </div>
    {% endif %}
    {% if not is_index_page %}
    <div class="mb-3">
        <form method="get" action="{% url 'planit:watch_application' %}">
            <label for="status">Фильтр по статусу:</label>
            <select name="status" id="status" onchange="this.form.submit()">
                <option value="">Все</option>
                {% for status_value, status_label in statuses %}
                    <option value="{{ status_value }}" {% if request.GET.status == status_value %}selected{% endif %}>
                        {{ status_label }}
                    </option>
                {% endfor %}
            </select>
            <label for="search">Поиск:</label>
            <input type="text" name="search" id="search" value="{{ request.GET.search }}" placeholder="Введите текст для поиска">
            
            <button type="submit">Поиск</button>
        </form>
    </div>
    {% endif %}

    {% if applications %}
        <div class="row">
            {% for application in applications %}
                <div class="col-6 mb-4"> 
                    <div class="card position-relative"> 
                        <div class="card-body">
                            <h5 class="card-title">{{ application.title }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ application.created_at|date:"d.m.Y H:i" }}</h6>
                            <p class="card-text">{{ application.description }}</p>
                            <p class="card-text"><strong>Категория:</strong> {{ application.category.name }}</p>
                            <p class="card-text"><strong>Статус:</strong> {{ application.get_status_display }}</p>
                            {% if application.image %}
                                <img src="{{ application.image.url }}" alt="Дизайн" style="width: 100%; height: 200px; border-radius: 6px; object-fit: cover;">
                            {% else %}
                                <div>Нет изображения</div>
                            {% endif %}
                            
                            {% if user.is_authenticated %}
                                <!-- Dropdown for actions -->
                                <div class="dropdown position-absolute" style="top: 10px; right: 10px;">
                                    <button class="btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="display: inline-block; transform: rotate(90deg); border: none; outline: none;">
                                        ...
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a  class="dropdown-item" href="{% url 'planit:update_application' application.id %}">Сменить статус</a>

                                        <!-- Delete Option -->
                                        <a class="dropdown-item" href="{% url 'planit:delete_application' application.id %}">Удалить</a>
                                        <a class="dropdown-item" href="{% url 'planit:application_detail' application.id %}">Посмотреть историю</a>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Нет доступных заявок.</p>
    {% endif %}
</div>

{% endblock %}